import React from 'react';
import { 
  Database, 
  ShieldCheck, 
  Scale, 
  Cpu, 
  Layers, 
  AlertCircle, 
  CheckCircle2,
  FileText
} from 'lucide-react';

export const TransparencyPage = () => {
  return (
    <div className="space-y-6 pb-16 max-w-5xl mx-auto">
      
      {/* Header */}
      <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-2xs">
        <div className="flex items-center gap-3">
          <div className="p-2.5 rounded-xl bg-blue-50 text-blue-800 border border-blue-200">
            <Database className="w-5 h-5" />
          </div>
          <div>
            <h2 className="text-xl font-bold text-slate-900 tracking-tight">Data Integrity & AI Methodology Transparency</h2>
            <p className="text-xs text-slate-500 mt-0.5">
              Open documentation on data pipelines, two-tier relational matching, Isolation Forest ML features, and explainable risk rules
            </p>
          </div>
        </div>
      </div>

      {/* Critical Legal & Ethical Statement */}
      <div className="bg-amber-50/90 border-l-4 border-amber-500 p-5 rounded-r-2xl shadow-2xs space-y-2">
        <div className="flex items-center gap-2">
          <AlertCircle className="w-5 h-5 text-amber-700 shrink-0" />
          <h3 className="text-xs font-bold text-amber-950 uppercase tracking-wider">
            Important Compliance & Ethical Standard
          </h3>
        </div>
        <p className="text-xs text-amber-900 leading-relaxed font-semibold">
          "Anomaly indicators generated by this platform are statistical decision-support signals designed to assist authorized government officers in prioritizing works for human review. They do not constitute proof or allegations of fraud, corruption, theft, or misconduct."
        </p>
        <p className="text-[11px] text-amber-800">
          The risk tiers (LOW, MEDIUM, HIGH, CRITICAL) and contributing factor weights are configurable prototype risk models for decision-support and do not represent statutory government audit findings.
        </p>
      </div>

      {/* 1. Dataset Provenance & Real Data Baseline */}
      <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-2xs space-y-4">
        <div className="flex items-center gap-2 border-b border-slate-100 pb-3">
          <Layers className="w-4 h-4 text-blue-700" />
          <h3 className="text-sm font-bold text-slate-900">1. Data Sources & Ingestion Scope</h3>
        </div>
        
        <p className="text-xs text-slate-600 leading-relaxed">
          The system processes verified raw datasets published under the official MPLADS Scheme portal:
        </p>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs">
          <div className="p-4 bg-slate-50 rounded-xl border border-slate-200">
            <h4 className="font-bold text-slate-900">MP Summary Dataset</h4>
            <p className="text-[11px] text-slate-500 mt-0.5">774 MPs across Lok Sabha and Rajya Sabha</p>
            <div className="mt-2.5 text-[11px] text-slate-800 space-y-1 font-mono">
              <div>Total Allocated: ₹1,16,767.91 Cr</div>
              <div>Total Expenditure: ₹39,599.36 Cr</div>
              <div>National Utilization: 33.91%</div>
            </div>
          </div>

          <div className="p-4 bg-slate-50 rounded-xl border border-slate-200">
            <h4 className="font-bold text-slate-900">Recommended & Completed Works</h4>
            <p className="text-[11px] text-slate-500 mt-0.5">83,797 Recommended Works • 43,667 Completed Works</p>
            <div className="mt-2.5 text-[11px] text-slate-800 space-y-1 font-mono">
              <div>Master Projects: 126,582 Records</div>
              <div>Direct Work ID Overlaps: 392</div>
              <div>Composite Normalized Matches: 2,589</div>
            </div>
          </div>

          <div className="p-4 bg-slate-50 rounded-xl border border-slate-200 sm:col-span-2">
            <h4 className="font-bold text-slate-900">Expenditures Dataset</h4>
            <p className="text-[11px] text-slate-500 mt-0.5">107,551 Transaction Vouchers</p>
            <div className="mt-1.5 text-[11px] text-slate-700 leading-relaxed">
              Contains vendor payment records. Identifies 38,866 exact duplicate occurrences and 40,114 repeated signature clusters across identical vendor/amount/MP combinations.
            </div>
          </div>
        </div>
      </div>

      {/* 2. Two-Tier Matching Methodology */}
      <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-2xs space-y-4">
        <div className="flex items-center gap-2 border-b border-slate-100 pb-3">
          <Scale className="w-4 h-4 text-blue-700" />
          <h3 className="text-sm font-bold text-slate-900">2. Relational Matching Methodology</h3>
        </div>

        <p className="text-xs text-slate-600 leading-relaxed">
          Because expenditure records and completion datasets in legacy government systems do not always share a unified foreign key, our pipeline applies a deterministic, multi-tier matching engine:
        </p>

        <div className="space-y-3 text-xs">
          <div className="p-3.5 bg-slate-50 rounded-xl border border-slate-200">
            <strong className="text-slate-900">Tier 1: Exact Work ID Match (Confidence: 1.0)</strong>
            <p className="text-slate-600 mt-0.5">
              Direct relational join on integer <code className="bg-slate-200 px-1 py-0.5 rounded font-mono">Work ID</code>.
            </p>
          </div>

          <div className="p-3.5 bg-slate-50 rounded-xl border border-slate-200">
            <strong className="text-slate-900">Tier 2: Composite Key Match (Confidence: 0.90)</strong>
            <p className="text-slate-600 mt-0.5">
              Composite hash of <code className="bg-slate-200 px-1 py-0.5 rounded font-mono">MP Name + Constituency + Normalized Work Description + IDA</code>.
            </p>
          </div>

          <div className="p-3.5 bg-slate-50 rounded-xl border border-slate-200">
            <strong className="text-slate-900">Unmatched Recommended Works Policy</strong>
            <p className="text-slate-600 mt-0.5">
              Recommended works without matching completion records are designated <span className="font-bold text-amber-800">"Completion Status Requires Verification"</span> rather than assumed delayed or failed.
            </p>
          </div>
        </div>
      </div>

      {/* 3. Hybrid AI: Rule Engine + Isolation Forest ML */}
      <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-2xs space-y-4">
        <div className="flex items-center gap-2 border-b border-slate-100 pb-3">
          <Cpu className="w-4 h-4 text-blue-700" />
          <h3 className="text-sm font-bold text-slate-900">3. Hybrid Explainable AI & Isolation Forest</h3>
        </div>

        <p className="text-xs text-slate-600 leading-relaxed">
          The system combines deterministic rule-based indicators with unsupervised machine learning to detect both known policy deviations and multi-dimensional statistical outliers:
        </p>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs">
          <div className="p-4 bg-slate-50 rounded-xl border border-slate-200">
            <h4 className="font-bold text-slate-900">A. Explainable Rule Indicators (Max 100 Pts)</h4>
            <ul className="mt-2.5 space-y-1 text-slate-700 list-disc list-inside">
              <li>Cost Anomaly: Up to 30 pts (&gt;25%, &gt;50%, &gt;100% cost deviation)</li>
              <li>Completion Concern: Up to 25 pts (Unverified / Delayed &gt;1yr)</li>
              <li>Payment Anomaly: Up to 20 pts (Over-budget / High frequency)</li>
              <li>Duplicate Concern: Up to 15 pts (Exact &amp; signature duplicates)</li>
              <li>Sector Similarity: Up to 10 pts (&gt;100% above peer median)</li>
            </ul>
          </div>

          <div className="p-4 bg-slate-50 rounded-xl border border-slate-200">
            <h4 className="font-bold text-slate-900">B. Unsupervised Isolation Forest (Scikit-learn)</h4>
            <p className="text-slate-700 mt-1 leading-relaxed">
              Trained on 11 numerical and encoded features without label leakage. Identifies 6.0% (7,595 works) multi-dimensional outliers across budget, duration, and transaction density vectors.
            </p>
            <p className="text-[11px] text-slate-500 mt-2 font-mono">
              Model: IsolationForest(n_estimators=120, contamination=0.06)
            </p>
          </div>
        </div>
      </div>

      {/* 4. Data Validation Confirmation */}
      <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-2xs space-y-3">
        <div className="flex items-center gap-2 border-b border-slate-100 pb-3">
          <ShieldCheck className="w-4 h-4 text-emerald-600" />
          <h3 className="text-sm font-bold text-slate-900">4. Live Data Validation Report</h3>
        </div>

        <div className="p-4 bg-emerald-50 rounded-xl border border-emerald-200 flex items-center gap-2.5 text-xs text-emerald-950 font-medium">
          <CheckCircle2 className="w-5 h-5 text-emerald-600 shrink-0" />
          <span>
            <strong>100% Exact Match Verified</strong>: All calculated system dashboard metrics match the official MoSPI reference baseline with zero discrepancy.
          </span>
        </div>
      </div>

    </div>
  );
};

export default TransparencyPage;
